version: "3.7"
services:
  db:
    hostname: db
    image: lnlscon/mailpy-db:v1.0
    ports:
      - 27017:27017
    build:
      context: ./db
    volumes:
      - mongo:/data/db
    networks:
      - mailpylocal

  mail:
    image: lnlscon/mailpy:v2.0
    build:
      context: ./mail
    network_mode: host # Required for broadcast forwarding
    secrets:
      - ALERT_MAIL_LOGIN
      - ALERT_MAIL_PASSWORD
    environment:
      # Set username and password if needed
      # mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
      MONGODB_URI: mongodb://db:27017/mailpy-db
#   volumes: # Use volumes so we can develop without docker swarm
#     - ./ALERT_MAIL_LOGIN:/run/secrets/ALERT_MAIL_LOGIN
#     - ./ALERT_MAIL_PASSWORD:/run/secrets/ALERT_MAIL_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - hostnet

  api:
    image: node:12.19.0-stretch
    working_dir: /app
    command: bash -c 'set -x; [[ ! -d node_modules || "$FORCE_INSTALL"=true ]] && npm install; [[ "$DEV"=true ]] && npm run dev || npm run start;'
    stdin_open: true # without this node doesn't start
    user: "${UID}:${GID}"
    environment:
      # Set username and password if needed
      # mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
      MONGODB_URI: mongodb://db:27017/mailpy-db
      NODE_ENV: development
      FORCE_INSTALL: "false"
      DEV: "true"
      API_SECRET: ""
    volumes:
      - "./api:/app"
    ports:
      - 1337:1337
    networks:
      - mailpylocal

  frontend:
    image: node:12.19.0-stretch
    working_dir: /app
    command: bash -c 'set -x; [[ ! -d node_modules || "$FORCE_INSTALL"=true ]] && npm install; npm run start;'
    stdin_open: true # without this node doesn't start
    user: "${UID}:${GID}"
    environment:
      API_URI: "https://localhost:1337"
      NODE_ENV: development
      FORCE_INSTALL: "false"
    volumes:
      - "./frontend:/app"
    ports:
      - 3006:3006
    networks:
      - mailpylocal

networks:
  hostnet:
    external:
      name: "host"
  mailpylocal:

volumes:
  mongo:

secrets:
  ALERT_MAIL_PASSWORD:
    external: true
  ALERT_MAIL_LOGIN:
    external: true
